<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\Bedroll.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      bedrollPacked_1: THREE.Mesh
      bedrollPacked_1_1: THREE.Mesh
      bedrollPacked_1_2: THREE.Mesh
    }
    materials: {
      foliage: THREE.MeshStandardMaterial
      wood: THREE.MeshStandardMaterial
      _defaultMat: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Bedroll.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.bedrollPacked_1.geometry} material={gltf.materials.foliage} />
    <T.Mesh geometry={gltf.nodes.bedrollPacked_1_1.geometry} material={gltf.materials.wood} />
    <T.Mesh geometry={gltf.nodes.bedrollPacked_1_2.geometry} material={gltf.materials._defaultMat} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
