<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\Bike.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Tire: THREE.Mesh
      Tire_1: THREE.Mesh
      ['Subdivision_Surface2-Mesh']: THREE.Mesh
      ['Subdivision_Surface2-Mesh_1']: THREE.Mesh
      ['Subdivision_Surface2-Mesh_2']: THREE.Mesh
    }
    materials: {
      Mat: THREE.MeshStandardMaterial
      ['Mat-2']: THREE.MeshStandardMaterial
      ['default']: THREE.MeshStandardMaterial
      ['Mat.2']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Bike.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Tire.geometry} material={gltf.materials.Mat} />
    <T.Mesh geometry={gltf.nodes.Tire_1.geometry} material={gltf.materials.Mat} />
    <T.Mesh geometry={gltf.nodes['Subdivision_Surface2-Mesh'].geometry} material={gltf.materials['Mat-2']} />
    <T.Mesh geometry={gltf.nodes['Subdivision_Surface2-Mesh_1'].geometry} material={gltf.materials['default']} />
    <T.Mesh geometry={gltf.nodes['Subdivision_Surface2-Mesh_2'].geometry} material={gltf.materials['Mat.2']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
