<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\Bike.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Tire: THREE.Mesh
      Tire_1: THREE.Mesh
      ['Subdivision_Surface2-Mesh']: THREE.Mesh
      ['Subdivision_Surface2-Mesh_1']: THREE.Mesh
      ['Subdivision_Surface2-Mesh_2']: THREE.Mesh
    }
    materials: {
      Mat: THREE.MeshStandardMaterial
      ['Mat-2']: THREE.MeshStandardMaterial
      ['default']: THREE.MeshStandardMaterial
      ['Mat.2']: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Bike.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Tire"
      geometry={gltf.nodes.Tire.geometry}
      material={gltf.materials.Mat}
    />
    <T.Mesh
      name="Tire_1"
      geometry={gltf.nodes.Tire_1.geometry}
      material={gltf.materials.Mat}
    />
    <T.Mesh
      name="Subdivision_Surface2-Mesh"
      geometry={gltf.nodes['Subdivision_Surface2-Mesh'].geometry}
      material={gltf.materials['Mat-2']}
    />
    <T.Mesh
      name="Subdivision_Surface2-Mesh_1"
      geometry={gltf.nodes['Subdivision_Surface2-Mesh_1'].geometry}
      material={gltf.materials['default']}
    />
    <T.Mesh
      name="Subdivision_Surface2-Mesh_2"
      geometry={gltf.nodes['Subdivision_Surface2-Mesh_2'].geometry}
      material={gltf.materials['Mat.2']}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
