<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\Campfire.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      campfire: THREE.Mesh
      bucket: THREE.Mesh
      rocks: THREE.Mesh
      wood: THREE.Mesh
    }
    materials: {
      wood: THREE.MeshStandardMaterial
      metal: THREE.MeshStandardMaterial
      rock: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Campfire.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="campfire"
      geometry={gltf.nodes.campfire.geometry}
      material={gltf.materials.wood}
    />
    <T.Mesh
      name="bucket"
      geometry={gltf.nodes.bucket.geometry}
      material={gltf.materials.metal}
    />
    <T.Mesh
      name="rocks"
      geometry={gltf.nodes.rocks.geometry}
      material={gltf.materials.rock}
    />
    <T.Mesh
      name="wood"
      geometry={gltf.nodes.wood.geometry}
      material={gltf.materials.wood}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
