<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\Campfire.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['Campfire_Cylinder009-Mesh']: THREE.Mesh
      ['Campfire_Cylinder009-Mesh_1']: THREE.Mesh
    }
    materials: {
      Stone: THREE.MeshStandardMaterial
      Wood: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Campfire.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['Campfire_Cylinder009-Mesh'].geometry} material={gltf.materials.Stone} />
    <T.Mesh geometry={gltf.nodes['Campfire_Cylinder009-Mesh_1'].geometry} material={gltf.materials.Wood} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
