<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\DingusTheCat.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Maxwell: THREE.Mesh
      whiskers: THREE.Mesh
    }
    materials: {
      Dingus: THREE.MeshStandardMaterial
      Whiskers: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/DingusTheCat.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="Maxwell"
      geometry={gltf.nodes.Maxwell.geometry}
      material={gltf.materials.Dingus}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      name="whiskers"
      geometry={gltf.nodes.whiskers.geometry}
      material={gltf.materials.Whiskers}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
