<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\DingusTheCat.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props, type Events, type Slots, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>
  type $$Events = Events<THREE.Group>
  type $$Slots = Slots<THREE.Group> & { fallback: {}; error: { error: any } }

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Maxwell: THREE.Mesh
      whiskers: THREE.Mesh
    }
    materials: {
      Dingus: THREE.MeshStandardMaterial
      Whiskers: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/DingusTheCat.glb')

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.Maxwell.geometry}
      material={gltf.materials.Dingus}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
    <T.Mesh
      geometry={gltf.nodes.whiskers.geometry}
      material={gltf.materials.Whiskers}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={100}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
