<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\GhostCompanion.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import type { Snippet } from 'svelte'
  import { onMount } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'
  import { ghostCompanion } from '$lib/stores'
  import { attachToCamera } from '$lib/animationHelpers'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  const ref = new Group()

  type ActionName = 'Mesh_0Action'
  type GLTFResult = {
    nodes: {
      Mesh_0: THREE.Mesh
    }
    materials: {
      Material_0: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/GhostCompanion.glb')

  export const { actions, mixer } = useGltfAnimations<ActionName>(gltf, ref)

  $effect(() => {
    ghostCompanion.set(ref)
  })

  onMount(() => {
    attachToCamera(ref, 0, true)

    const interval = setInterval(() => {
      const action = actions.current['Mesh_0Action'] as THREE.AnimationAction

      if (action) {
        clearInterval(interval)
        action.play()
      }
    }, 50)

    return () => {
      clearInterval(interval)
    }
  })
</script>

<T
  is={ref}
  dispose={false}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group name="Scene">
      <T.Mesh
        name="Mesh_0"
        geometry={gltf.nodes.Mesh_0.geometry}
        material={gltf.materials.Material_0}
        position={[-0.02, 1.48, 0.02]}
        rotation={[-0.04, -0.04, 0.04]}
        scale={0.98}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T>
