<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\GrassPlatform.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      ['GrassPlatform_Cylinder001-Mesh']: THREE.Mesh
      ['GrassPlatform_Cylinder001-Mesh_1']: THREE.Mesh
    }
    materials: {
      Dirt: THREE.MeshStandardMaterial
      Grass: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/GrassPlatform.glb')
</script>

<T is={ref} dispose={false} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['GrassPlatform_Cylinder001-Mesh'].geometry} material={gltf.materials.Dirt} />
    <T.Mesh geometry={gltf.nodes['GrassPlatform_Cylinder001-Mesh_1'].geometry} material={gltf.materials.Grass} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>

