<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\InfoBoard.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      ParkInfoBoard_1: THREE.Mesh
      ParkInfoBoard_2: THREE.Mesh
      ParkInfoBoard_3: THREE.Mesh
    }
    materials: {
      wood_shade1: THREE.MeshStandardMaterial
      board: THREE.MeshStandardMaterial
      wood_shade2: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/InfoBoard.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="ParkInfoBoard"
      position={[0, 0.75, 0]}
      rotation={[-Math.PI / 2, 0, 0]}
      scale={[36.33, 40, 40]}
    >
      <T.Mesh
        name="ParkInfoBoard_1"
        geometry={gltf.nodes.ParkInfoBoard_1.geometry}
        material={gltf.materials.wood_shade1}
      />
      <T.Mesh
        name="ParkInfoBoard_2"
        geometry={gltf.nodes.ParkInfoBoard_2.geometry}
        material={gltf.materials.board}
      />
      <T.Mesh
        name="ParkInfoBoard_3"
        geometry={gltf.nodes.ParkInfoBoard_3.geometry}
        material={gltf.materials.wood_shade2}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
