<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\Shovel.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      toolShovel_1: THREE.Mesh
      toolShovel_1_1: THREE.Mesh
      toolShovel_1_2: THREE.Mesh
    }
    materials: {
      wood: THREE.MeshStandardMaterial
      metal: THREE.MeshStandardMaterial
      _defaultMat: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Shovel.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="toolShovel_1"
      geometry={gltf.nodes.toolShovel_1.geometry}
      material={gltf.materials.wood}
    />
    <T.Mesh
      name="toolShovel_1_1"
      geometry={gltf.nodes.toolShovel_1_1.geometry}
      material={gltf.materials.metal}
    />
    <T.Mesh
      name="toolShovel_1_2"
      geometry={gltf.nodes.toolShovel_1_2.geometry}
      material={gltf.materials._defaultMat}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
