<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\threlte.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      Cube: THREE.Mesh
    }
    materials: {
      Material: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/threlte.glb')
</script>

<T is={ref} dispose={false} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.Cube.geometry} material={gltf.materials.Material} position={[0, 1, 2]} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>

