<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 D:\repos\IGORnvk.github.io\static\models\TreeLarge.glb --root /models/ --types --printwidth 120 --precision 2
-->

<script lang="ts">
  import type * as THREE from 'three'
  import { Group } from 'three'
  import { T, type Props } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  type $$Props = Props<THREE.Group>

  export const ref = new Group()

  type GLTFResult = {
    nodes: {
      treeLarge_1: THREE.Mesh
      treeLarge_1_1: THREE.Mesh
    }
    materials: {
      wood: THREE.MeshStandardMaterial
      foliage: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/TreeLarge.glb')
</script>

<T is={ref} dispose={false} {...$$restProps}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes.treeLarge_1.geometry} material={gltf.materials.wood} />
    <T.Mesh geometry={gltf.nodes.treeLarge_1_1.geometry} material={gltf.materials.foliage} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>

