<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\Tulips.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      mesh1524081558: THREE.Mesh
      mesh1524081558_1: THREE.Mesh
      mesh1160013864: THREE.Mesh
      mesh1160013864_1: THREE.Mesh
      mesh1653023134: THREE.Mesh
      mesh1653023134_1: THREE.Mesh
      mesh1653023134_2: THREE.Mesh
      mesh1741665748: THREE.Mesh
      mesh1741665748_1: THREE.Mesh
      mesh1741665748_2: THREE.Mesh
      mesh605848671: THREE.Mesh
      mesh605848671_1: THREE.Mesh
      mesh605848671_2: THREE.Mesh
      mesh875356185: THREE.Mesh
      mesh875356185_1: THREE.Mesh
      mesh1418125784: THREE.Mesh
      mesh1418125784_1: THREE.Mesh
      mesh1699578894: THREE.Mesh
      mesh1699578894_1: THREE.Mesh
      mesh2026508287: THREE.Mesh
      mesh2026508287_1: THREE.Mesh
      mesh2026508287_2: THREE.Mesh
      mesh1869555222: THREE.Mesh
      mesh1869555222_1: THREE.Mesh
      mesh1869555222_2: THREE.Mesh
      group305020849: THREE.Mesh
      group1315161051: THREE.Mesh
      mesh1336710718: THREE.Mesh
      mesh1336710718_1: THREE.Mesh
      mesh1336710718_2: THREE.Mesh
      group1126844985: THREE.Mesh
      mesh1662392388: THREE.Mesh
      mesh1662392388_1: THREE.Mesh
      mesh1662392388_2: THREE.Mesh
      mesh1563464038: THREE.Mesh
      mesh1563464038_1: THREE.Mesh
      mesh1563464038_2: THREE.Mesh
      mesh369730231: THREE.Mesh
      mesh369730231_1: THREE.Mesh
      mesh369730231_2: THREE.Mesh
      mesh64326919: THREE.Mesh
      mesh64326919_1: THREE.Mesh
      mesh64326919_2: THREE.Mesh
      group133156713: THREE.Mesh
      group1548105374: THREE.Mesh
      group1731819144: THREE.Mesh
      mesh773970968: THREE.Mesh
      mesh773970968_1: THREE.Mesh
      mesh773970968_2: THREE.Mesh
      mesh1513215620: THREE.Mesh
      mesh1513215620_1: THREE.Mesh
      mesh1548443602: THREE.Mesh
      mesh1548443602_1: THREE.Mesh
      mesh371625766: THREE.Mesh
      mesh371625766_1: THREE.Mesh
      mesh371625766_2: THREE.Mesh
      group574375989: THREE.Mesh
      group340541725: THREE.Mesh
      group528986637: THREE.Mesh
      mesh201291130: THREE.Mesh
      mesh201291130_1: THREE.Mesh
      mesh201291130_2: THREE.Mesh
      mesh647133167: THREE.Mesh
      mesh647133167_1: THREE.Mesh
      mesh647133167_2: THREE.Mesh
      group743581695: THREE.Mesh
      mesh1089069114: THREE.Mesh
      mesh1089069114_1: THREE.Mesh
      mesh1089069114_2: THREE.Mesh
      group1051964877: THREE.Mesh
      mesh851135502: THREE.Mesh
      mesh851135502_1: THREE.Mesh
      mesh851135502_2: THREE.Mesh
      group1517434150: THREE.Mesh
      mesh1294012767: THREE.Mesh
      mesh1294012767_1: THREE.Mesh
      mesh1294012767_2: THREE.Mesh
      mesh1195982837: THREE.Mesh
      mesh1195982837_1: THREE.Mesh
      mesh1195982837_2: THREE.Mesh
      group25708318: THREE.Mesh
      group1376070046: THREE.Mesh
      mesh1219209497: THREE.Mesh
      mesh1219209497_1: THREE.Mesh
      mesh1219209497_2: THREE.Mesh
      group1204995636: THREE.Mesh
      mesh1035713103: THREE.Mesh
      mesh1035713103_1: THREE.Mesh
      mesh1035713103_2: THREE.Mesh
      mesh797648510: THREE.Mesh
      mesh797648510_1: THREE.Mesh
      mesh478565310: THREE.Mesh
      mesh478565310_1: THREE.Mesh
      mesh478565310_2: THREE.Mesh
      mesh445126197: THREE.Mesh
      mesh445126197_1: THREE.Mesh
      mesh445126197_2: THREE.Mesh
      mesh1367787382: THREE.Mesh
      mesh1367787382_1: THREE.Mesh
      mesh1587333848: THREE.Mesh
      mesh1587333848_1: THREE.Mesh
      mesh1587333848_2: THREE.Mesh
      mesh472026721: THREE.Mesh
      mesh472026721_1: THREE.Mesh
      mesh472026721_2: THREE.Mesh
      mesh472026721_3: THREE.Mesh
      mesh941805466: THREE.Mesh
      mesh941805466_1: THREE.Mesh
      mesh941805466_2: THREE.Mesh
      mesh941805466_3: THREE.Mesh
      mesh1199946381: THREE.Mesh
      mesh1199946381_1: THREE.Mesh
      mesh1199946381_2: THREE.Mesh
      mesh1199946381_3: THREE.Mesh
    }
    materials: {
      mat11: THREE.MeshStandardMaterial
      mat10: THREE.MeshStandardMaterial
      mat9: THREE.MeshStandardMaterial
      mat7: THREE.MeshStandardMaterial
      mat0: THREE.MeshStandardMaterial
      mat1: THREE.MeshStandardMaterial
      mat6: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/Tulips.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Mesh
      name="group305020849"
      geometry={gltf.nodes.group305020849.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1315161051"
      geometry={gltf.nodes.group1315161051.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1126844985"
      geometry={gltf.nodes.group1126844985.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group133156713"
      geometry={gltf.nodes.group133156713.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1548105374"
      geometry={gltf.nodes.group1548105374.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1731819144"
      geometry={gltf.nodes.group1731819144.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group574375989"
      geometry={gltf.nodes.group574375989.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group340541725"
      geometry={gltf.nodes.group340541725.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group528986637"
      geometry={gltf.nodes.group528986637.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group743581695"
      geometry={gltf.nodes.group743581695.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1051964877"
      geometry={gltf.nodes.group1051964877.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1517434150"
      geometry={gltf.nodes.group1517434150.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group25708318"
      geometry={gltf.nodes.group25708318.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1376070046"
      geometry={gltf.nodes.group1376070046.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="group1204995636"
      geometry={gltf.nodes.group1204995636.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="mesh1524081558"
      geometry={gltf.nodes.mesh1524081558.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1524081558_1"
      geometry={gltf.nodes.mesh1524081558_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1160013864"
      geometry={gltf.nodes.mesh1160013864.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1160013864_1"
      geometry={gltf.nodes.mesh1160013864_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1653023134"
      geometry={gltf.nodes.mesh1653023134.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1653023134_1"
      geometry={gltf.nodes.mesh1653023134_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1653023134_2"
      geometry={gltf.nodes.mesh1653023134_2.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh1741665748"
      geometry={gltf.nodes.mesh1741665748.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1741665748_1"
      geometry={gltf.nodes.mesh1741665748_1.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh1741665748_2"
      geometry={gltf.nodes.mesh1741665748_2.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh605848671"
      geometry={gltf.nodes.mesh605848671.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh605848671_1"
      geometry={gltf.nodes.mesh605848671_1.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh605848671_2"
      geometry={gltf.nodes.mesh605848671_2.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh875356185"
      geometry={gltf.nodes.mesh875356185.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh875356185_1"
      geometry={gltf.nodes.mesh875356185_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1418125784"
      geometry={gltf.nodes.mesh1418125784.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1418125784_1"
      geometry={gltf.nodes.mesh1418125784_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1699578894"
      geometry={gltf.nodes.mesh1699578894.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1699578894_1"
      geometry={gltf.nodes.mesh1699578894_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh2026508287"
      geometry={gltf.nodes.mesh2026508287.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh2026508287_1"
      geometry={gltf.nodes.mesh2026508287_1.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh2026508287_2"
      geometry={gltf.nodes.mesh2026508287_2.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1869555222"
      geometry={gltf.nodes.mesh1869555222.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1869555222_1"
      geometry={gltf.nodes.mesh1869555222_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1869555222_2"
      geometry={gltf.nodes.mesh1869555222_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1336710718"
      geometry={gltf.nodes.mesh1336710718.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1336710718_1"
      geometry={gltf.nodes.mesh1336710718_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1336710718_2"
      geometry={gltf.nodes.mesh1336710718_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1662392388"
      geometry={gltf.nodes.mesh1662392388.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1662392388_1"
      geometry={gltf.nodes.mesh1662392388_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1662392388_2"
      geometry={gltf.nodes.mesh1662392388_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1563464038"
      geometry={gltf.nodes.mesh1563464038.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh1563464038_1"
      geometry={gltf.nodes.mesh1563464038_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1563464038_2"
      geometry={gltf.nodes.mesh1563464038_2.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh369730231"
      geometry={gltf.nodes.mesh369730231.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh369730231_1"
      geometry={gltf.nodes.mesh369730231_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh369730231_2"
      geometry={gltf.nodes.mesh369730231_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh64326919"
      geometry={gltf.nodes.mesh64326919.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh64326919_1"
      geometry={gltf.nodes.mesh64326919_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh64326919_2"
      geometry={gltf.nodes.mesh64326919_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh773970968"
      geometry={gltf.nodes.mesh773970968.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh773970968_1"
      geometry={gltf.nodes.mesh773970968_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh773970968_2"
      geometry={gltf.nodes.mesh773970968_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1513215620"
      geometry={gltf.nodes.mesh1513215620.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1513215620_1"
      geometry={gltf.nodes.mesh1513215620_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1548443602"
      geometry={gltf.nodes.mesh1548443602.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1548443602_1"
      geometry={gltf.nodes.mesh1548443602_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh371625766"
      geometry={gltf.nodes.mesh371625766.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh371625766_1"
      geometry={gltf.nodes.mesh371625766_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh371625766_2"
      geometry={gltf.nodes.mesh371625766_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh201291130"
      geometry={gltf.nodes.mesh201291130.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh201291130_1"
      geometry={gltf.nodes.mesh201291130_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh201291130_2"
      geometry={gltf.nodes.mesh201291130_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh647133167"
      geometry={gltf.nodes.mesh647133167.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh647133167_1"
      geometry={gltf.nodes.mesh647133167_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh647133167_2"
      geometry={gltf.nodes.mesh647133167_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1089069114"
      geometry={gltf.nodes.mesh1089069114.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1089069114_1"
      geometry={gltf.nodes.mesh1089069114_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1089069114_2"
      geometry={gltf.nodes.mesh1089069114_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh851135502"
      geometry={gltf.nodes.mesh851135502.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh851135502_1"
      geometry={gltf.nodes.mesh851135502_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh851135502_2"
      geometry={gltf.nodes.mesh851135502_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1294012767"
      geometry={gltf.nodes.mesh1294012767.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1294012767_1"
      geometry={gltf.nodes.mesh1294012767_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1294012767_2"
      geometry={gltf.nodes.mesh1294012767_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1195982837"
      geometry={gltf.nodes.mesh1195982837.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1195982837_1"
      geometry={gltf.nodes.mesh1195982837_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1195982837_2"
      geometry={gltf.nodes.mesh1195982837_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1219209497"
      geometry={gltf.nodes.mesh1219209497.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1219209497_1"
      geometry={gltf.nodes.mesh1219209497_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1219209497_2"
      geometry={gltf.nodes.mesh1219209497_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh1035713103"
      geometry={gltf.nodes.mesh1035713103.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1035713103_1"
      geometry={gltf.nodes.mesh1035713103_1.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1035713103_2"
      geometry={gltf.nodes.mesh1035713103_2.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh797648510"
      geometry={gltf.nodes.mesh797648510.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh797648510_1"
      geometry={gltf.nodes.mesh797648510_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh478565310"
      geometry={gltf.nodes.mesh478565310.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh478565310_1"
      geometry={gltf.nodes.mesh478565310_1.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh478565310_2"
      geometry={gltf.nodes.mesh478565310_2.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh445126197"
      geometry={gltf.nodes.mesh445126197.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh445126197_1"
      geometry={gltf.nodes.mesh445126197_1.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh445126197_2"
      geometry={gltf.nodes.mesh445126197_2.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1367787382"
      geometry={gltf.nodes.mesh1367787382.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh1367787382_1"
      geometry={gltf.nodes.mesh1367787382_1.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1587333848"
      geometry={gltf.nodes.mesh1587333848.geometry}
      material={gltf.materials.mat10}
    />
    <T.Mesh
      name="mesh1587333848_1"
      geometry={gltf.nodes.mesh1587333848_1.geometry}
      material={gltf.materials.mat9}
    />
    <T.Mesh
      name="mesh1587333848_2"
      geometry={gltf.nodes.mesh1587333848_2.geometry}
      material={gltf.materials.mat11}
    />
    <T.Mesh
      name="mesh472026721"
      geometry={gltf.nodes.mesh472026721.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="mesh472026721_1"
      geometry={gltf.nodes.mesh472026721_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh472026721_2"
      geometry={gltf.nodes.mesh472026721_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh472026721_3"
      geometry={gltf.nodes.mesh472026721_3.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh941805466"
      geometry={gltf.nodes.mesh941805466.geometry}
      material={gltf.materials.mat1}
    />
    <T.Mesh
      name="mesh941805466_1"
      geometry={gltf.nodes.mesh941805466_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh941805466_2"
      geometry={gltf.nodes.mesh941805466_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh941805466_3"
      geometry={gltf.nodes.mesh941805466_3.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="mesh1199946381"
      geometry={gltf.nodes.mesh1199946381.geometry}
      material={gltf.materials.mat6}
    />
    <T.Mesh
      name="mesh1199946381_1"
      geometry={gltf.nodes.mesh1199946381_1.geometry}
      material={gltf.materials.mat7}
    />
    <T.Mesh
      name="mesh1199946381_2"
      geometry={gltf.nodes.mesh1199946381_2.geometry}
      material={gltf.materials.mat0}
    />
    <T.Mesh
      name="mesh1199946381_3"
      geometry={gltf.nodes.mesh1199946381_3.geometry}
      material={gltf.materials.mat1}
    />
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
