<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\WoodenSign10.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Sign8_1: THREE.Mesh
      Sign8_2: THREE.Mesh
      Sign8_3: THREE.Mesh
    }
    materials: {
      ['Dark Wood']: THREE.MeshStandardMaterial
      ['Light Wood']: THREE.MeshStandardMaterial
      Herbs: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/WoodenSign10.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="Sign8"
      scale={100}
    >
      <T.Mesh
        name="Sign8_1"
        geometry={gltf.nodes.Sign8_1.geometry}
        material={gltf.materials['Dark Wood']}
      />
      <T.Mesh
        name="Sign8_2"
        geometry={gltf.nodes.Sign8_2.geometry}
        material={gltf.materials['Light Wood']}
      />
      <T.Mesh
        name="Sign8_3"
        geometry={gltf.nodes.Sign8_3.geometry}
        material={gltf.materials.Herbs}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
