<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.0.0-next.11 C:\Users\igork\Documents\Code\igornvk.github.io\static\models\WoodenSign7.glb --root /models/ --types --keepnames --printwidth 120 --precision 2 --isolated
-->

<script lang="ts">
  import type * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  let {
    fallback,
    error,
    children
  }: {
    children?: Snippet
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Sign11_1: THREE.Mesh
      Sign11_2: THREE.Mesh
      Sign11_3: THREE.Mesh
      Sign11_4: THREE.Mesh
    }
    materials: {
      Herbs: THREE.MeshStandardMaterial
      ['Dark Wood']: THREE.MeshStandardMaterial
      ['Light Wood']: THREE.MeshStandardMaterial
      Rocks: THREE.MeshStandardMaterial
    }
  }

  const gltf = useGltf<GLTFResult>('/models/WoodenSign7.glb')
</script>

<T.Group dispose={false}>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      name="Sign11"
      scale={100}
    >
      <T.Mesh
        name="Sign11_1"
        geometry={gltf.nodes.Sign11_1.geometry}
        material={gltf.materials.Herbs}
      />
      <T.Mesh
        name="Sign11_2"
        geometry={gltf.nodes.Sign11_2.geometry}
        material={gltf.materials['Dark Wood']}
      />
      <T.Mesh
        name="Sign11_3"
        geometry={gltf.nodes.Sign11_3.geometry}
        material={gltf.materials['Light Wood']}
      />
      <T.Mesh
        name="Sign11_4"
        geometry={gltf.nodes.Sign11_4.geometry}
        material={gltf.materials.Rocks}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.()}
</T.Group>
